name: AI code review

on:
  pull_request:
    types: [ready_for_review]
  # pull_request_target:
  #   types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Robin AI Reviewer
        uses: Integral-Healthcare/robin-ai-reviewer@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          files_to_ignore: |
            "yarn.lock
